name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Extract version from build.sh
      id: get_version
      run: |
        VERSION=$(grep '^version=' build.sh | cut -d'"' -f2)
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Extracted version: $VERSION"
    
    - name: Build and push Docker image
      env:
        # Docker Hub credentials
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        # Quay.io credentials
        QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
        QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
        # GitHub Container Registry uses GITHUB_TOKEN automatically
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./build.sh
    
    - name: Create GitHub Release
      if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.get_version.outputs.VERSION }}
        name: SRBMiner-Multi v${{ steps.get_version.outputs.VERSION }}
        body: |
          ## SRBMiner-Multi Docker Image v${{ steps.get_version.outputs.VERSION }}
          
          Docker images successfully built and pushed to:
          - Docker Hub: `docker.io/cniweb/srbminer-multi:${{ steps.get_version.outputs.VERSION }}`
          - GitHub Container Registry: `ghcr.io/cniweb/srbminer-multi:${{ steps.get_version.outputs.VERSION }}`
          - Quay.io: `quay.io/cniweb/srbminer-multi:${{ steps.get_version.outputs.VERSION }}`
          
          ### Usage
          ```bash
          docker pull cniweb/srbminer-multi:${{ steps.get_version.outputs.VERSION }}
          ```
          
          Based on [SRBMiner-Multi ${{ steps.get_version.outputs.VERSION }}](https://github.com/doktor83/SRBMiner-Multi/releases/tag/${{ steps.get_version.outputs.VERSION }})
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
